from utility import *

# eg("crash", "show crashing behavior", crashFunc)
# eg("the", "show settings", oo)
# eg("sym","check syms", symFunc)
# eg("num", "check nums", numFunc)
# eg("data", "read DATA csv", dataFunc)
# eg("clone", "duplicate structure", cloneFunc)
# eg("around", "sorting nearest neighbors", aroundFunc)
# eg("half", "1-level bi-clustering", halfFunc)
# eg("cluster", "N-level bi-clustering", clusterFunc)
# eg("optimize", "semi-supervised optimization", swayFunc)
# eg("repcols", "checking repcols", repColsFunc)
#eg("synonyms","checking repcols cluster", synonymsFunc)
eg("reprows","checking reprows", reprowsFunc)
